global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "default-receiver"

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: "http://dummy:5000/" # Test endpoint

# Example for Slack (uncomment and configure):
# - name: 'slack-notifications'
#   slack_configs:
#   - api_url: 'https://hooks.slack.com/services/XXXX/YYYY/ZZZZ'
#     channel: '#alerts'
#     send_resolved: true

# Example for Email (uncomment and customize):
# - name: 'email-admin'
#   email_configs:
#   - to: 'admin@example.com'
#     from: 'alertmanager@example.com'
#     smarthost: 'smtp.example.com:587'
#     auth_username: 'user@example.com'
#     auth_password: 'password'
